Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::group(array("prefix" => "admin", "as"=>"admin."), function () {
        Route::group(['middleware' => 'auth:dcms'], function () {

            //DEALERS
            Route::group(array("prefix" => "dealers", "as"=>"dealers."), function () {
                Route::get("{id}/copy", array("as"=>"copy", "uses" => "DealerController@copy"));
                Route::get("api/zipcity", array("as"=>"api.zipcity", "uses" => "DealerController@getZipCityJson"));
                Route::any("api/table", array( "as" => "api.table", "uses" => "DealerController@getDatatable"));
                Route::any("api/closurerow", array("as"=>"api.closurerow", "uses" => "DealerController@getClosureRow"));
                Route::any("map", array( "as" => "map", "uses" => "DealerController@map"));
                Route::any("fillnullgps", array( "as" => "map", "uses" => "DealerController@fillNullGps"));
            });
            Route::resource("dealers", "DealerController");
        });
    });
});

Http/Controllers/DealerController.php
<?php

namespace Dcms\Dealers\Http\Controllers;

use Dcms\Core\Http\Controllers\BaseController;
use Dcms\Dealers\Models\Dealer;
use Dcms\Dealers\Models\Closure;
use Dcms\Dealers\Models\Opening;
use Dcms\Dealers\Models\Zipcity;
use Dcms\Dealers\Models\ZipcityNL;
use Illuminate\Http\Request;
use View;
use Session;
use Validator;
use Redirect;
use DB;
use DataTables;
use Auth;
use Schema;
use DateTime;
use Form;

class DealerController extends BaseController
{
    public $countries = [];
    public $extendFormTemplate = "";
    public $ColumNames = [];
    public $ColumnNamesDefaults = []; // e.g. checkboxes left blank will result in NULL database value, if this is not what you want, you can set e.g. array('checkbox_name'=>'0');

    public function __construct()
    {
        $this->middleware('permission:dealers-browse')->only('index');
        $this->middleware('permission:dealers-add')->only(['create', 'store']);
        $this->middleware('permission:dealers-edit')->only(['edit', 'update']);
        $this->middleware('permission:dealers-delete')->only('destroy');

        $this->extendformTemplate = null;
        $this->ColumNames = array_merge($this->ColumNames, ['dealer' => 'dealer', 'address' => 'address', 'zip' => 'zip', 'city' => 'city', 'country_id' => 'country_id', 'phone' => 'phone', 'email' => 'email', 'contactemail' => 'contactemail', 'attention'=>'attention', 'website' => 'website']);
        $this->ColumnNamesDefaults = array_merge($this->ColumnNamesDefaults, ['country_id' => '1']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $filtercolumns = ['dealer' => 'dealer', 'city' => 'city', 'country' => 'country (ISO 3166-2)', 'procenter' => 'pro', 'sector' => 'sector'];
        return View::make('dcms::dealers/index')->with('filtercolumns', $filtercolumns);
    }

    public function map(Request $request)
    {
        $mapMarkers = "";

        if ($request->server("REQUEST_METHOD") == "POST") {
            $SQLDealers = Dealer::where('country_id', 'LIKE', '%');
            if ($request->has('country_id') && $request->get('country_id') > 0) {
                $SQLDealers = Dealer::where('country_id', 'LIKE', $request->get('country_id'));
            }

            if (strlen($request->get('search')) > 0) {
                $SQLDealers = $SQLDealers->where(function ($query) use ($request) {
                    $query->where('dealer', 'LIKE', $request->get('search'));
                    $query->orWhere('address', 'LIKE', $request->get('search'));
                    $query->orWhere('city', 'LIKE', $request->get('search'));
                });
            }

            $Dealers = $SQLDealers->get();

            if ($Dealers->count() > 0) {
                foreach ($Dealers as $Dealer) {
                    $thisDealer = "";

                    if (strlen(trim($Dealer->regiocode)) <= 0) {
                        $vRegiocode = "";
                    } else {
                        $vRegiocode = trim($Dealer->regiocode);
                    }

                    $detaillink = "http://www.dcm-info.be/nl/hobby/verkooppunten/";

                    if ($Dealer->country_id == '2' && $Dealer->procenter == '1') {
                        $detaillink = "http://www.dcm-info.nl/pro/verkooppunten/";
                    } elseif ($Dealer->country_id == '2' && $Dealer->procenter == '0') {
                        $detaillink = "http://www.dcm-info.nl/hobby/verkooppunten/";
                    } elseif ($Dealer->country_id == '3') {
                        $detaillink = "http://www.dcm-info.fr/hobby/points-de-vente/";
                    }

                    $thisDealer = $thisDealer . "<h3><a href='" . $detaillink . $Dealer->id . "/" . str_slug($Dealer->dealer) . "/' target='_parent'> " . $Dealer->dealer . "</a></h3>";
                    $http = "http";

                    if (intval($Dealer->partner) == 1) {
                        $thisDealer = $thisDealer . "<img src='" . $http . "://www.dcm-info.com/images/dealer/nl/partner.png' alt='Partner' class='premium' />";
                    }
                    if (intval($Dealer->premium) == 1) {
                        $thisDealer = $thisDealer . "<img src='" . $http . "://www.dcm-info.com/images/dealer/nl/premium.png' alt='Premium' class='premium' />";
                    }
                    if (intval($Dealer->aquanatura) == "1") {
                        $thisDealer = $thisDealer . "<img src='" . $http . "://www.dcm-info.com/images/dealer/nl/aqua.png' alt='Aqua Natura' />";
                    }
                    if (intval($Dealer->webshop) == "1") {
                        $thisDealer = $thisDealer . "<a href='" . $Dealer->website . "'><img src='" . $http . "://www.dcm-info.com/images/dealer/nl/webshop.png' alt='webshop' class='webshop' /></a>";
                    }
                    $thisDealer .= "<p>";

                    if (strlen(trim($Dealer->address)) > 0) {
                        $thisDealer .= $Dealer->address . "<br />";
                    }

                    if (strlen(trim($Dealer->zip)) > 0) {
                        $thisDealer .= $Dealer->zip . "  " . $vRegiocode . " " . $Dealer->city . "<br />";
                    }

                    if (strlen(trim($Dealer->phone)) > 0) {
                        $thisDealer .= "<i class='fa fa-phone'></i> " . $Dealer->phone . "<br />";
                    }
                    //if(strlen(trim($Dealer->fax))>0) 		$thisDealer .= "<i class='fa fa-print'></i> " . $Dealer->fax . "<br />" ;
                    if (strlen(trim($Dealer->email)) > 0) {
                        $thisDealer .= "<i class='fa fa-envelope-o'></i> <a href='mailto:" . $Dealer->email . "'>" . $Dealer->email . "</a><br />";
                    }

                    if (strlen($Dealer->website) > 0) {
                        if (strpos($Dealer->website, "http://") >= 0 || strpos($Dealer->website, "https://") >= 0) {
                            $website = $Dealer->website;
                        } else {
                            $website = "http://" . $Dealer->website;
                        }
                        $thisDealer = $thisDealer . "<i class='fa fa-laptop'></i> <a href='" . $website . "' target='_blank'> " . str_replace("http://", "", $website) . "</a><br />";
                    } //'end if website check
                    /*'==============================================================================================================================================================*/

                    $thisDealer .= "</p>";
                    $thisDealer .= '<form method="POST" action="/admin/dealers/' . $Dealer->id . '" accept-charset="UTF-8" class="pull-right"> <input name="_token" type="hidden" value="' . csrf_token() . '"> <input name="_method" type="hidden" value="DELETE"><a class="btn btn-xs btn-default" href="/admin/dealers/' . $Dealer->id . '/edit"><i class="fa fa-pencil"></i></a><button class="btn btn-xs btn-default" type="submit" value="Delete this article" onclick="if(!confirm(\'Are you sure to delete this item?\')){return false;};"><i class="fa fa-trash-o"></i></button></form>';
                    $icon = "gmap_pin1.png";
                    $type = "default";

                    if ($Dealer->premium == 1 && $Dealer->country_id == 1) {
                        $icon = "gmap_pin3.png";
                        $type = "premium";
                    }

                    if ($Dealer->partner == 1) {
                        $icon = "gmap_pin4.png";
                        $type = "partner";
                    }
                    
                    if ($Dealer->premium == 1 && $Dealer->country_id <> 1) {
                        $icon = "gmap_pin5.png";
                        $type = "extended";
                    }
                    
                    $mapMarkers .=  ",{
                        position: new google.maps.LatLng(" . $Dealer->latitude . ", " . $Dealer->longitude . "),
                        title: '".str_replace("'", "", $Dealer->dealer)."',
                        info: '".str_replace("'", '"', $thisDealer)."',
                        zindex: ". $Dealer->id.",
                        type: '".$type."'
                    }";
                }
                $mapMarkers = substr($mapMarkers, 1);
            }
        }
        // load the view
        return View::make('dcms::dealers/map')->withInput($request->all())->with('mapMarkers', $mapMarkers);
    }

    public function getZipCityJson(Request $request)
    {
        $zipcity = trim($request->get("zipcity"));
        $country_id = trim($request->get("country_id"));
        
        if ($country_id == "1") {
            return Zipcity::select('postcode as zip', 'gemeente as city', (DB::connection('admin')->table('admin')->raw('CONCAT(postcode, " ", gemeente) AS label')))->where('postcode', 'LIKE', $zipcity . '%')->orwhere('gemeente', 'LIKE', '%' . $zipcity . '%')->get()->toJson();
        } else {
            return ZipcityNL::select('postcode as zip', 'gemeente as city', (DB::connection('admin')->table('admin')->raw('CONCAT(postcode, " ", gemeente) AS label')))->where('postcode', 'LIKE', $zipcity . '%')->orwhere('gemeente', 'LIKE', '%' . $zipcity . '%')->get()->toJson();
        }
    }

    public function getDatatable()
    {
        $query = DB::connection('project')
            ->table('dealers')->select("dealers.id", "dealers.dealer", "dealers.code", "dealers.address", "dealers.zip", "dealers.city", (DB::connection("project")->raw("concat(\"<img src='/packages/dcms/core/images/flag-\", lcase(countries.country),\".png' > \") as country")), 'longitude', 'latitude')
            ->leftJoin("countries", "countries.id", "=", "dealers.country_id");

        if (Session::has('dealerfilter.colname')) {
            $filter = Session::get('dealerfilter');
            foreach ($filter['colname'] as $i => $colname) {

resources/views/dealers/form.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Dealers</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{!! URL::to('admin/dealers') !!}"><i class="fa fa-pencil"></i> Dealers</a></li>
            @if(isset($dealer))
                <li class="active">Edit</li>
            @else
                <li class="active">Create</li>
            @endif
        </ol>
        @if(isset($dealer))
            <p class="edit">Last edited by {{ $dealer->admin }} on {{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $dealer->updated_at)->format('d-m-Y H:i:s') }}</p>
        @endif
    </div>

    <div class="main-content">
        <div class="row">

            @if(isset($dealer))
                {!! Form::model($dealer, array('route' => array('admin.dealers.update', $dealer->id), 'method' => 'PUT')) !!}
            @else
                {!! Form::open(array('url' => 'admin/dealers')) !!}
            @endif



            @if(!is_null($extendformTemplate["template"]))
                @include($extendformTemplate["template"], array('dealer'=>(isset($dealer)?$dealer:null)))
            @endif

            <div class="col-md-12">
                <div class="main-content-tab tab-container">

                    <ul class="nav nav-tabs" role="tablist">
                        <li class="active"><a href="#data" role="tab" data-toggle="tab">Data</a></li>
                        <li><a href="#closures" role="tab" data-toggle="tab">Closure</a></li>
                        <li><a href="#openings" role="tab" data-toggle="tab">Openings</a></li>
                    </ul>

                    <div class="tab-content">

                        @if($errors->any())
                            <div class="alert alert-danger">{!! HTML::ul($errors->all()) !!}</div>
                        @endif

                        <div id="data" class="tab-pane active">

                            <div class="form-group">
                                {!! Form::label('dealer', 'Dealer') !!}
                                {!! Form::text('dealer', null, array('class' => 'form-control')) !!}
                            </div>

                            <div class="form-group">
                                {!! Form::label('address', 'Address') !!}
                                {!! Form::text('address', null, array('class' => 'form-control')) !!}
                            </div>

                            <div class="row">
                                <div class="col-sm-2">

                                    <div class="form-group">
                                        {!! Form::label('zip', 'Zip') !!}
                                        {!! Form::text('zip', null, array('class' => 'form-control')) !!}
                                    </div>

                                </div>
                                <div class="col-sm-10">
                                    <div class="form-group">
                                        {!! Form::label('city', 'City') !!}
                                        {!! Form::text('city', null, array('class' => 'form-control')) !!}
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                {!! Form::label('country_id', 'Country') !!}
                                {!! Form::select('country_id', $countries, old('country_id'), array('class' => 'form-control')) !!}
                            </div>

                            <div class="form-group">
                                {!! Form::label('longitude', 'longitude') !!}
                                {!! Form::text('longitude', null, array('class' => 'form-control')) !!}
                            </div>

                            <div class="form-group">
                                {!! Form::label('latitude', 'Latitude') !!}
                                {!! Form::text('latitude', null, array('class' => 'form-control')) !!}
                            </div>


                            <div class="form-group">
                                {!! Form::label('phone', 'Phone') !!}
                                {!! Form::text('phone', null, array('class' => 'form-control')) !!}
                            </div>

                            <div class="form-group">
                                {!! Form::label('email', 'Email') !!}<span class="hidden">Shown on the dealer page on the websites</span>
                                {!! Form::text('email', null, array('class' => 'form-control')) !!}
                            </div>

                            <div class="form-group">
                                {!! Form::label('contactemail', 'Contact email') !!} <span class="hidden">Naturapy&reg;</span>
                                {!! Form::text('contactemail', null, array('class' => 'form-control')) !!}
                            </div>

                            <div class="form-group">
                                {!! Form::label('website', 'Website') !!}
                                {!! Form::text('website', "http://".str_replace(["http://", "https://"],"",(isset($dealer->website)?$dealer->website:old('website'))), array('class' => 'form-control')) !!}
                            </div>

                        </div>


                            <div id="closures" class="tab-pane">

                                <div id="closure">
                                    <table class="table table-bordered table-striped ">
                                        <thead>
                                        <tr>
                                            <th>Startdate dd/mm/yyyy (first day of closing)</th>
                                            <th>Enddate dd/mm/yyyy (last day of closing)</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        @if(isset($rowClosure))
                                            {!! $rowClosure !!}
                                        @endif
                                        <tfoot>
                                        <tr>
                                            <td colspan="5"><a class="btn btn-default pull-right add-table-row" href=""><i
                                                            class="fa fa-plus"></i></a></td>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>

                            </div>

                            <div id="openings" class="tab-pane">

                                @for($i = 1; $i <= 7; $i++)
                                    <div class="row">
                                        <div class="col-xs-6 col-md-2">
                                            <div class="form-group">
                                                <p class="form-control-static" style="margin: 10px 0"><b>{{ jddayofweek($i - 1, 1) }}</b></p>
                                            </div>
                                        </div>

                                        <div class="col-xs-6 col-md-2">
                                            {!! Form::checkbox('open_'.$i , 1, $openings->where('opening_day', $i)->first(), array('class' => 'form-checkbox' , 'id' => 'open_'.$i)) !!}
                                            {!! Form::label('open_'.$i, "&nbsp;", array('class' => ($openings->where('opening_day', $i)->first())?'checkbox active':'checkbox')) !!}
                                        </div>
                                        @for($j = 1; $j <= 4; $j++)
                                            <div class="col-xs-6 col-md-2">
                                                <div class="form-group">
                                                    <input type="time" id="opening_hour_{{$j}}[{{$i}}]" name="opening_hour_{{$j}}[{{$i}}]"
                                                           class="form-control"
                                                           value="{{ $errors->any() ? old('opening_hour_' . $j . '.' . $i) : ($openings->where('opening_day', $i)->first() && $openings->where('opening_day', $i)->first()->{'opening_hour_' . $j} ? Carbon\Carbon::createFromFormat('H:i:s', $openings->where('opening_day', $i)->first()->{'opening_hour_' . $j})->format('H:i') : null)}}">
                                                </div>
                                            </div>
                                        @endfor
                                    </div>
                                @endfor

                                <div class="row">

                                    <div class="col-xs-6 col-md-2">
                                        <div class="form-group">
                                            AM (00:00 - 11:59)<br/>
                                            PM (12:00 - 23:59)<br/><br/>
                                        </div>
                                    </div>

                                    <div class="col-xs-6 col-md-2">
                                        <div class="form-group">
                                            12:00 AM = midnight (00:00)<br/>
                                            12:00 PM = midday (12:00)
                                        </div>
                                    </div>

                                </div>
                            </div>

                    </div><!-- end tab-content -->
                </div><!-- end main-content-tab -->
            </div><!-- end col-md-12 -->

            <div class="col-md-12">
                <div class="main-content-block">
                    {!! Form::submit('Save', array('class' => 'btn btn-primary')) !!}
                    <a href="{!! URL::previous() !!}" class="btn btn-default">Cancel</a>
                </div>
            </div>

            {!! Form::close() !!}

        </div><!-- end row -->
    </div><!-- end main-content -->

@stop

@section("script")

    <script type="text/javascript">
        $(document).ready(function () {

            //Bootstrap Tabs
            $(".tab-container .nav-tabs a").click(function (e) {
                e.preventDefault()
                $(this).tab('show')
            })

            //UI Autocomplete Product Detail
            $(".main-content-block input[id='zip'], .main-content-block input[id='city']").autocomplete({
                source: function (request, response) {
                    var country_id = $("#country_id").val();
                    $.getJSON("{!! route('admin.dealers.api.zipcity') !!}?zipcity=" + request.term + "&country_id=" + country_id, function (data) {
                        response(data);
                    });
                },
                select: function (event, ui) {
                    $(this).val(ui.item.label);
                    $(this).closest(".main-content-block").find("input[id='zip']").val(ui.item.zip);
                    $(this).closest(".main-content-block").find("input[id='city']").val(ui.item.city);
                    return false;
                },
                minLength: 1,
                delay: 200
            });

        });
    </script>

    <script type="text/javascript" src="{!! asset('packages/dcms/core/js/bootstrap.min.js') !!}"></script>
    <script type="text/javascript" src="{!! asset('packages/dcms/core/js/jquery-ui-autocomplete.min.js') !!}"></script>
    <link rel="stylesheet" type="text/css" href="{!! asset('packages/dcms/core/css/jquery-ui-autocomplete.css') !!}">

    <script language="javascript" type="application/javascript">

        $(document).ready(function () {



            //Add table row
            $.fn.addtablerow = function (options) {

                $(this).each(function () {

                    var table = $(this);

                    var rows = table.closest('tbody tr').length;

                    table.find('.add-table-row').click(function () {
                        //  language_id = table.attr("class").replace('table table-bordered table-striped ','');
                        geturl = options.source;
                        //  geturl = geturl.replace("{LANGUAGE_ID}",language_id);

                        $.get(geturl, function (data) {
                            if (!table.find('tbody').length) table.find('thead').after("<tbody></tbody>");

                            data = data.replace(/{INDEX}/g, "extra" + "-" + rows);
                            table.find('tbody').append(data);
                            //$("#attachment-language-id[extra"+rows+"] option[value='"+language_id+"']").attr('selected','selected');
                            rows++;
                            deltablerow(table.find('.delete-table-row').last());
                        });
                        return false;
                    });

                    deltablerow(table.find('.delete-table-row'));

                    function deltablerow(e) {
                        e.click(function () {
                            $(this).closest("tr").remove();
                            if (!table.find('tbody tr').length) table.find('tbody').remove();
                            return false;
                        });
                    }

                });

            };


            $("#closure table").addtablerow({
                source: "{!! URL::to('admin/dealers/api/closurerow?data=closure') !!}" //generate the row with the dropdown fields/empty boxes/etc.
            });
        });

    </script>

@stop

resources/views/dealers/map.blade.php
@extends("dcms::template/layout")

@section("content")
    <div class="main-header">
        <h1>Dealers</h1>
        <ol class="breadcrumb">
            <li><a href="{{ URL::to('admin/dashboard') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{{ URL::to('admin/dealers') }}"><i class="fa fa-map-marker"></i> Dealers</a></li>
            <li class="active"><i class="fa fa-map-marker"></i> Map</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">
                    <h2>Filter</h2>
                    {!! Form::open(array('url' => 'admin/dealers/map')) !!}

                    <div class="form-group">
                        {!! Form::label('search_id', 'Search (Dealer, Address, City)') !!}
                        {!! Form::text('search', request()->get('search'), array('class' => 'form-control')) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('country_id', 'Country') !!}
                        {!! Form::select('country_id', array('0'=>'-','1' => 'Belgium', '2' => 'Netherlands', '3' => 'France', '4' => 'Germany'),request()->get('country_id'), array('class' => 'form-control')) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::submit('Set filter', array('class' => 'btn btn-primary')) !!}
                        <a href="{!! URL::previous() !!}" class="btn btn-default">Reset filter</a>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
            <div class="col-md-12">
                <div class="main-content-block no-padding">
                    <div id="dealermap"></div>
                </div>
            </div>
        </div>
    </div>
@stop

@section("script")
    <?php
    /*
    ini_set('error_reporting', E_ALL);
    ini_set('display_errors', '1');
    */

    $minZoom = 12; //'a better name would be maxZoom - 12 has been defined as highest zoom, (20 is maximum, but not relevant) 12-08-2010


    //$latitude = $minLatitude + ($difLatitude/2);
    //$longitude = $minLongitude + ($difLongitude/2);
    ?>

    <script>

        function initMap() {

            var initCenter = new google.maps.LatLng(50.56318, 4.69528);
            var initZoom = 7;

            var map = new google.maps.Map(document.getElementById('dealermap'), {
                zoom: initZoom,
                center: initCenter
            });
            var bounds = new google.maps.LatLngBounds();

            var dealers = [
                {!!$mapMarkers!!}
            ];

            var iconBase = '/packages/dcms/dealers/images/marker/';
            var icons = {
                'default': {url: iconBase + 'default.svg', scaledSize: new google.maps.Size(28, 34)},
                'extended': {url: iconBase + 'extended.svg', scaledSize: new google.maps.Size(28, 34)},
                'premium': {url: iconBase + 'premium.svg', scaledSize: new google.maps.Size(28, 34)},
                'partner': {url: iconBase + 'partner.svg', scaledSize: new google.maps.Size(28, 34)}
            };

            var infowindow = new google.maps.InfoWindow();

            dealers.forEach(function (dealer) {

                var marker = new google.maps.Marker({
                    position: dealer.position,
                    icon: icons[dealer.type],
                    map: map,
                    zIndex: dealer.zindex,
                    optimized: false,
                });

                bounds.extend(dealer.position);
                map.fitBounds(bounds);

                google.maps.event.addListener(marker, 'click', function () {
                    infowindow.close();
                    infowindow.setContent(dealer.info);
                    infowindow.open(map, marker);
                });
            });

            var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function (event) {
                google.maps.event.removeListener(boundsListener);
            });
        }
    </script>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ env('GOOGLE_MAPS_KEY') }}&callback=initMap"></script>

@stop